# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  lerna:
    docker:
      - image: pickmyload/circleci-lerna:latest
        user: node
        auth:
          username: danimbrognopml  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
  base:
    machine:
      image: circleci/classic:201808-01
jobs:
  checkout:
    executor: lerna
    steps:
      - checkout:
          path: ~/repo
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
            - .ssh/known_hosts
  bootstrap:
    executor: lerna
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/repo && lerna bootstrap --ci && lerna run build
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  publishRelease:
    executor: lerna
    steps:
      - attach_workspace:
          at: ~/
      - run: git config --global user.email "dan@pmlfreight.tech" && git config --global user.name "CircleCI"
      - run: "cd ~/repo && lerna publish --conventional-commits --yes --message=\"chore(release): publish release %v [skip ci]\""
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  publishCanary:
    executor: lerna
    steps:
      - attach_workspace:
          at: ~/
      - run: git config --global user.email "dan@pmlfreight.tech" && git config --global user.name "CircleCI"
      - run: "cd ~/repo && lerna publish --canary"
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  buildImage:
    executor: base
    parameters:
      image:
        description: "What image do you want to build?"
        default: "A"
        type: enum
        enum: ["A", "B"]
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/repo && ./build/build-container.sh << parameters.image >>
  deploy:
    executor: base
    parameters:
      environment:
        description: "Where should we deploy?"
        default: "stage"
        type: enum
        enum: ["stage", "demo", "prod"]
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/repo && ./deploy/deploy.sh << parameters.environment >>
workflows:
  version: 2
  deploy_staging:
    jobs:
      - checkout:
          filters:
            branches:
              only: next
      - bootstrap:
          requires:
            - checkout
      - publishCanary:
          requires:
            - bootstrap
      - buildImage:
          image: A
          requires:
            - publishCanary
      - buildImage:
          image: B
          requires:
            - publishCanary
  # deploy_demo_and_prod:
  #   jobs:
  #     - checkout:
  #         filters:
  #           branches:
  #             only: master
  #     - deploy:
  #         environment: demo
  #         requires:
  #           - checkout
  #     - deploy:
  #         environment: prod
  #         requires:
  #           - checkout